### PR TITLE
Add french README and nvs init in main.c

### PR DESCRIPTION
**Pull request by Grillon**
* wifi needs nvs initialization.
* french people probably doesn't need a translation but it's
free.
* add wifi, gpio, nvs and system support to mirb.

### CODE REVIEW

**Comment by Grillon** [comment]
Hi, I'm really excited to see mruby working on esp32. It was easy to install and use. Few dependencies were missing, so I have added them in that pull request.

Best regards,

Thierry

PS : it's my first pull request so if I did something wrong please tell me.

**Comment by pandax381** [comment]
Thank you for your pull request.
Sorry for the late response.

The translation of README is very grateful!

I hope this mirb will be the easiest way to run mruby on ESP32. Therefore, we do not include ESP32 specific mrbgems by default. I expect them to incorporate it by themselves as needed.

I want to you please change to a pull request for translation only.

**Comment by Grillon** [comment]
Hi thank you for reply. I have removed mgems. What about nvs_flash_init() in main.c?

**Comment by pandax381** [comment]
Thanks!
main.c also has no problem.

**Pull request merged**
